paths:
  /devolucion:
    get:
      summary: Obtener todas las devoluciones
      description: Retorna una lista de todas las devoluciones registradas en el sistema.
      tags:
        - Devoluciones
      responses:
        '200':
          description: Lista de devoluciones obtenida con éxito.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    iddevolucion:
                      type: integer
                      description: ID único de la devolución.
                      example: 1
                    fecharealizada:
                      type: string
                      format: date
                      description: Fecha en que se realizó la devolución.
                      example: "2025-01-15"
                    motivo:
                      type: string
                      description: Motivo o razón de la devolución.
                      example: "Producto defectuoso - no funciona correctamente"
                    monto:
                      type: number
                      format: float
                      description: Monto de la devolución.
                      example: 150.75
                    idventa:
                      type: integer
                      description: ID de la venta asociada a la devolución.
                      example: 5
                    created_at:
                      type: string
                      format: date-time
                      description: Fecha de creación del registro de devolución.
                      example: "2025-01-15T10:30:00.000Z"
                    updated_at:
                      type: string
                      format: date-time
                      description: Fecha de última actualización del registro de devolución.
                      example: "2025-01-15T10:30:00.000Z"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error.
                    example: "An error occurred while retrieving devolution."
    post:
      summary: Crear una nueva devolución
      description: Registra una nueva devolución en el sistema.
      tags:
        - Devoluciones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - iddevolucion
                - fecharealizada
                - motivo
                - monto
                - idventa
              properties:
                iddevolucion:
                  type: integer
                  description: ID único de la devolución.
                  example: 1
                fecharealizada:
                  type: string
                  format: date
                  description: Fecha en que se realizó la devolución.
                  example: "2025-01-15"
                motivo:
                  type: string
                  description: Motivo o razón de la devolución.
                  example: "Producto defectuoso - no funciona correctamente"
                monto:
                  type: number
                  format: float
                  minimum: 0
                  description: Monto de la devolución (debe ser mayor o igual a 0).
                  example: 150.75
                idventa:
                  type: integer
                  description: ID de la venta asociada a la devolución.
                  example: 5
      responses:
        '200':
          description: Devolución creada con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito.
                    example: "Devolution added successfully."
        '400':
          description: Solicitud incorrecta. Errores de validación.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de error.
                    example: "Validation errors."
                  errors:
                    type: array
                    description: Lista de errores de validación.
                    items:
                      type: string
                    example: 
                      - "iddevolution is required."
                      - "date made is required."
                      - "motive is required."
                      - "Price cannot be negative or null."
                      - "idventa is required."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error.
                    example: "An error occurred while adding the devolution to the system."
  /devolucion/{iddevolucion}:
    get:
      summary: Obtener una devolución por ID
      description: Retorna los detalles de una devolución específica basada en su ID.
      tags:
        - Devoluciones
      parameters:
        - name: iddevolucion
          in: path
          required: true
          description: ID único de la devolución a consultar.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Detalles de la devolución obtenidos con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  iddevolucion:
                    type: integer
                    description: ID único de la devolución.
                    example: 1
                  fecharealizada:
                    type: string
                    format: date
                    description: Fecha en que se realizó la devolución.
                    example: "2025-01-15"
                  motivo:
                    type: string
                    description: Motivo o razón de la devolución.
                    example: "Producto defectuoso - no funciona correctamente"
                  monto:
                    type: number
                    format: float
                    description: Monto de la devolución.
                    example: 150.75
                  idventa:
                    type: integer
                    description: ID de la venta asociada a la devolución.
                    example: 5
                  created_at:
                    type: string
                    format: date-time
                    description: Fecha de creación del registro de devolución.
                    example: "2025-01-15T10:30:00.000Z"
                  updated_at:
                    type: string
                    format: date-time
                    description: Fecha de última actualización del registro de devolución.
                    example: "2025-01-15T10:30:00.000Z"
        '404':
          description: Devolución no encontrada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de error.
                    example: "Devolution not found."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error.
                    example: "An error occurred while retrieving the devolution."
  /tallerrepuestos/devoluciones/crear:
    post:
      tags:
        - Devoluciones Sistema de Pagos
      summary: Crear una nueva devolución en el sistema de pagos
      description: Crea una devolución para una transacción específica en el sistema externo de pagos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - NoTransaccion
                - Monto
                - Descripcion
              properties:
                NoTransaccion:
                  type: number
                  description: Número de la transacción a devolver
                  example: 12345
                Monto:
                  type: number
                  description: Monto a devolver
                  minimum: 0.01
                  example: 150.00
                Descripcion:
                  type: string
                  description: Descripción de la devolución
                  example: "Producto defectuoso"
      responses:
        '201':
          description: Devolución creada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Devolución creada exitosamente"
                  devolucion:
                    type: object
                    properties:
                      Mensaje:
                        type: string
                        example: "Devolucion realizada correctamente"
        '400':
          description: Datos faltantes o inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Faltan datos requeridos: NoTransaccion, Monto, Descripcion"
        '500':
          description: Error interno del servidor

  /tallerrepuestos/devoluciones/obtener:
    get:
      tags:
        - Devoluciones Sistema de Pagos
      summary: Obtener todas las devoluciones del sistema de pagos
      description: Obtiene todas las devoluciones, opcionalmente filtradas por rango de fechas.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fechaInicio:
                  type: string
                  format: date-time
                  description: Fecha de inicio del filtro (opcional)
                  example: "2024-01-01T00:00:00Z"
                fechaFinal:
                  type: string
                  format: date-time
                  description: Fecha final del filtro (opcional)
                  example: "2024-12-31T23:59:59Z"
      responses:
        '200':
          description: Lista de devoluciones obtenida exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Devoluciones obtenidas exitosamente"
                  devoluciones:
                    type: array
                    items:
                      $ref: '#/components/schemas/DevolucionPagos'
                  total:
                    type: number
                    description: Total de devoluciones encontradas
                    example: 5
        '500':
          description: Error interno del servidor

  /tallerrepuestos/devoluciones/obtener/{noDevolucion}:
    get:
      tags:
        - Devoluciones Sistema de Pagos
      summary: Obtener devolución por número
      description: Obtiene los detalles de una devolución específica por su número.
      parameters:
        - name: noDevolucion
          in: path
          required: true
          schema:
            type: number
          description: Número de la devolución
          example: 12345
      responses:
        '200':
          description: Devolución encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Devolución obtenida exitosamente"
                  devolucion:
                    type: object
                    properties:
                      Devolucion:
                        $ref: '#/components/schemas/DevolucionPagos'
        '400':
          description: Número de devolución inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "El número de devolución debe ser un número válido"
        '404':
          description: Devolución no encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Devolución no encontrada"
        '500':
          description: Error interno del servidor

components:
  schemas:
    DevolucionPagos:
      type: object
      properties:
        NoDevolucion:
          type: number
          description: Número único de la devolución
          example: 12345
        NoTransaccion:
          type: number
          description: Número de la transacción asociada
          example: 67890
        Monto:
          type: number
          description: Monto devuelto
          example: 150.00
        Descripcion:
          type: string
          description: Descripción de la devolución
          example: "Producto defectuoso"
        NoAutorizacion:
          type: string
          description: Número de autorización de la devolución
          example: "AUTH-DEV-2024-001"
        Fecha:
          type: string
          format: date-time
          description: Fecha y hora de la devolución
          example: "2024-01-15T14:30:00Z"
        NotaCredito:
          type: string
          description: Número de nota de crédito generada
          example: "NC-2024-001"
