paths:
  /tiposervicios:
    get:
      summary: Obtener todos los tipos de servicio
      description: Retorna una lista de todos los tipos de servicio registrados en el sistema.
      tags:
        - Tipos de Servicio
      responses:
        '200':
          description: Lista de tipos de servicio obtenida con éxito.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    idtiposervicio:
                      type: integer
                      description: ID único del tipo de servicio.
                      example: 1
                    descripcion:
                      type: string
                      description: Descripción del tipo de servicio.
                      example: "Mantenimiento del vehiculo"
                    costo:
                      type: string
                      format: float
                      description: Costo del tipo de servicio.
                      example: "500.00"
                    tiposervicio:
                      type: string
                      description: Categoría o tipo del servicio.
                      example: "Mantenimiento general"
                    status:
                      type: integer
                      description: Estado del tipo de servicio (1 = activo, 0 = inactivo).
                      example: 1
                    created_at:
                      type: string
                      format: date-time
                      description: Fecha de creación del tipo de servicio.
                      example: "2025-04-12T03:17:56.623Z"
                    updated_at:
                      type: string
                      format: date-time
                      description: Fecha de última actualización del tipo de servicio.
                      example: "2025-04-12T03:17:56.623Z"
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error.
                    example: "Internal Server Error"
    post:
      summary: Crear un nuevo tipo de servicio
      description: Agrega un nuevo tipo de servicio al sistema.
      tags:
        - Tipos de Servicio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descripcion:
                  type: string
                  description: Descripción del tipo de servicio.
                  example: "Mantenimiento del vehiculo"
                costo:
                  type: string
                  format: float
                  description: Costo del tipo de servicio.
                  example: "500.00"
                tiposervicio:
                  type: string
                  description: Categoría o tipo del servicio.
                  example: "Mantenimiento general"
      responses:
        '201':
          description: Tipo de servicio creado con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito.
                    example: "Service type added successfully"
        '400':
          description: Solicitud incorrecta. Faltan campos obligatorios.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de error.
                    example: "Bad Request. Please fill all fields."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error.
                    example: "Internal Server Error"
  /tiposervicios/{idtiposervicio}:
    get:
      summary: Obtener un tipo de servicio por ID
      description: Retorna los detalles de un tipo de servicio específico basado en su ID.
      tags:
        - Tipos de Servicio
      parameters:
        - name: idtiposervicio
          in: path
          required: true
          description: ID único del tipo de servicio a consultar.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Detalles del tipo de servicio obtenidos con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  idtiposervicio:
                    type: integer
                    description: ID único del tipo de servicio.
                    example: 1
                  descripcion:
                    type: string
                    description: Descripción del tipo de servicio.
                    example: "Mantenimiento del vehiculo"
                  costo:
                    type: string
                    format: float
                    description: Costo del tipo de servicio.
                    example: "500.00"
                  tiposervicio:
                    type: string
                    description: Categoría o tipo del servicio.
                    example: "Mantenimiento general"
                  status:
                    type: integer
                    description: Estado del tipo de servicio (1 = activo, 0 = inactivo).
                    example: 1
                  created_at:
                    type: string
                    format: date-time
                    description: Fecha de creación del tipo de servicio.
                    example: "2025-04-12T03:17:56.623Z"
                  updated_at:
                    type: string
                    format: date-time
                    description: Fecha de última actualización del tipo de servicio.
                    example: "2025-04-12T03:17:56.623Z"
        '404':
          description: Tipo de servicio no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de error.
                    example: "Service type not found."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error.
                    example: "Internal Server Error"
    put:
      summary: Actualizar un tipo de servicio existente
      description: Actualiza los datos de un tipo de servicio registrado en el sistema.
      tags:
        - Tipos de Servicio
      parameters:
        - name: idtiposervicio
          in: path
          required: true
          description: ID único del tipo de servicio a actualizar.
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descripcion:
                  type: string
                  description: Descripción del tipo de servicio.
                  example: "Mantenimiento del vehiculo"
                costo:
                  type: string
                  format: float
                  description: Costo del tipo de servicio.
                  example: "500.00"
                tiposervicio:
                  type: string
                  description: Categoría o tipo del servicio.
                  example: "Mantenimiento general"
      responses:
        '200':
          description: Tipo de servicio actualizado con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito.
                    example: "Service type updated successfully"
        '400':
          description: Solicitud incorrecta. Faltan campos obligatorios o el ID no es válido.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de error.
                    example: "Bad Request. Please fill all fields."
        '404':
          description: Tipo de servicio no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de error.
                    example: "Service type not found."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error.
                    example: "Internal Server Error"
    delete:
      summary: Eliminar un tipo de servicio
      description: Cambia el estado de un tipo de servicio a inactivo en el sistema.
      tags:
        - Tipos de Servicio
      parameters:
        - name: idtiposervicio
          in: path
          required: true
          description: ID único del tipo de servicio a eliminar.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Tipo de servicio eliminado con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de éxito.
                    example: "Service type deleted successfully"
        '404':
          description: Tipo de servicio no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de error.
                    example: "Service type not found."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error.
                    example: "Internal Server Error"